# Generated by Django 4.2.3 on 2023-07-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_cards',
            new_name='all_card',
        ),
    ]
